Add php8 compatibility
drupalauth/simplesamlphp-module-drupalauth pull request #80
Opened 2022-01-24 03:18 UTC by patrickharriscatalyst

I ran phpcs phpcompatability on this module and found no errors or warnings. Can we tentatively add support for PHP8?

2022-01-24 20:42 UTC, RoSk0 commented
Thanks!

Can you please also add PHP 8 to the test matrix https://github.com/drupalauth/simplesamlphp-module-drupalauth/blob/master/.travis.yml#L6

2022-01-24 23:32 UTC, RoSk0 commented
Sadly I discovered that Travis CI no longer builds this project. Unfortunately, until I figure out the direction for CI I'm not in a position to accept this change.

2022-01-26 21:38 UTC, RoSk0 commented
Now that we have CI back, can you please add 8.1 to Composer as well?

2022-01-26 21:54 UTC, patrickharriscatalyst commented
Isn't 8.1 covered by `^8.0` in composer.json?

2022-01-26 22:07 UTC, RoSk0 commented
Yes, you are right, but explicit is always better than implicit. 

Please add PHP 8.1 to composer.json.

2022-01-26 22:22 UTC, patrickharriscatalyst commented
Done!

2022-01-29 02:49 UTC, RoSk0 commented on .travis.yml
> +   - '8.1'
```suggestion
   - '8.1.0'
```

It looks like we need full version atm for 8.1.

See https://travis-ci.community/t/php-8-1-support/12439/23 for details

2022-02-01 01:57 UTC, RoSk0 requested changes

2022-02-01 01:57 UTC, RoSk0 commented on .travis.yml
> +   - '8.1.0'
```suggestion
```

Looks like Travis is not completely ready for 8.1 so we are not going to rush either.

2022-02-01 01:57 UTC, RoSk0 commented on composer.json
> +    "php": "^5.6.0|^7.0|^8.0|^8.1",
```suggestion
    "php": "^5.6.0|^7.0|^8.0",
```

2022-02-01 02:02 UTC, merged

2022-02-01 02:02 UTC, RoSk0 commented
Thanks Patrick!